<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FightsRepository extends EntityRepository
{
}
