<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * gladiatorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gladiatorsRepository extends EntityRepository
{
}
