<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * gladStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gladStatsRepository extends EntityRepository
{
}
