<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * gladArmorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gladArmorRepository extends EntityRepository
{
}
