<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerStatsRepository extends EntityRepository
{
}
